aux = input('Infome algo para verificarmos ')
print('o tipo primitivo é ', type(aux))
print('É um numero alfa numérico? ',aux.isalnum())
print('É um numero alfa? ',aux.isalpha())
print('É um numero decimal? ',aux.isdecimal())
print('É um numero digit? ',aux.isdigit())
print('É um numero identifier? ',aux.isidentifier())
print('É algo minusculo? ',aux.islower())
print('É um numero? ',aux.isnumeric())
print('É um printable? ',aux.isprintable())
print('É um space? ',aux.isspace())
print('É um titulo? ',aux.istitle())
print('É um maiusculo? ',aux.isupper())